# Dynamic Python environment for use with direnv
#
# This file is the base template. The actual shell.nix used by projects
# is generated by the use_python_env direnvrc function, which embeds
# the resolved package list from requirements.txt or pyproject.toml.
#
# Usage in .envrc:
#   use_python_env           # Normal mode with activation message
#   use_python_env --quiet   # Suppress activation message
#
# The function will:
# 1. Parse requirements.txt or pyproject.toml
# 2. Map pip names to nixpkgs names via pip-to-nix.json
# 3. Generate .direnv/python-shell.nix with resolved packages
# 4. Call use nix on the generated file
#
# See: nix/modules/home/direnv.nix for the use_python_env implementation
{ pkgs ? import <nixpkgs> {}
, packages ? []  # List of nixpkgs python package names (e.g., ["pillow" "pyyaml"])
, quiet ? false  # Suppress activation message
}:

let
  my-python = pkgs.python3;

  # Resolve package names to actual python packages
  # Gracefully skip packages that don't exist in nixpkgs
  resolvePackage = name:
    if builtins.hasAttr name my-python.pkgs
    then my-python.pkgs.${name}
    else builtins.trace "Warning: Python package '${name}' not found in nixpkgs, skipping" null;

  resolvedPackages = builtins.filter (p: p != null) (map resolvePackage packages);

  python-with-packages = my-python.withPackages (_ps: resolvedPackages);

  packageCount = builtins.length resolvedPackages;
  packageList = builtins.concatStringsSep ", " packages;
in
pkgs.mkShell {
  name = "python-env";

  buildInputs = [ python-with-packages ];

  shellHook = ''
    # Fix PYTHONPATH to include nix packages
    # See: https://github.com/NixOS/nixpkgs/issues/61144
    PYTHONPATH=${python-with-packages}/${python-with-packages.sitePackages}
    export PYTHONPATH

    # Create .venv symlink structure for IDE detection
    # IDEs like VS Code, PyCharm look for .venv/bin/python
    if [ ! -L .venv ] || [ "$(readlink .venv)" != "${python-with-packages}" ]; then
      rm -rf .venv 2>/dev/null || true
      ln -sf ${python-with-packages} .venv
    fi

    # Export VIRTUAL_ENV for tools that use it
    export VIRTUAL_ENV="$PWD/.venv"

    ${if !quiet then ''
    echo "🐍 Python environment activated"
    echo "   Python: $(python3 --version)"
    ${if packageCount > 0 then ''echo "   Packages (${toString packageCount}): ${packageList}"'' else ''echo "   Packages: (none)"''}
    echo "   IDE path: .venv/bin/python"
    '' else ""}
  '';
}
